# Generated by Django 5.0 on 2023-12-15 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_users_is_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='user_name',
            new_name='username',
        ),
    ]
