# Generated by Django 5.0 on 2023-12-17 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_users_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='file_id',
        ),
        migrations.RemoveField(
            model_name='files',
            name='file_path',
        ),
        migrations.AddField(
            model_name='files',
            name='file_compressed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='files',
            name='file_store',
            field=models.FileField(default=0, upload_to='../uploads/'),
        ),
        migrations.AddField(
            model_name='files',
            name='user_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='files',
            name='file_size',
            field=models.PositiveIntegerField(default=0, verbose_name='file size(in Bytes)'),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=256, verbose_name='user_password'),
        ),
        migrations.DeleteModel(
            name='FileInfo',
        ),
    ]
