# Generated by Django 5.0 on 2023-12-17 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_files_file_id_remove_files_file_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='user_id',
            field=models.IntegerField(unique=True),
        ),
    ]
