# Generated by Django 5.0 on 2023-12-17 21:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_users_is_admin_alter_users_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file_store',
            field=models.FileField(upload_to='../uploads/2023-12-17 21:42:24.781208'),
        ),
        migrations.AlterField(
            model_name='files',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
