# Generated by Django 5.0 on 2023-12-17 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_files_file_store_alter_files_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file_store',
            field=models.FileField(upload_to='../uploads/2023-12-17 21:49:06.984555'),
        ),
    ]
