# Generated by Django 5.0 on 2023-12-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_files_file_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='file_compressed',
        ),
        migrations.RemoveField(
            model_name='files',
            name='file_size',
        ),
        migrations.AddField(
            model_name='files',
            name='file_name',
            field=models.CharField(db_column='name', default='file_name', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='files',
            name='file_store',
            field=models.FileField(upload_to='../uploads/2023-12-18 10:56:26.102363'),
        ),
    ]
